server:
  port: 31001
spring:
  datasource:
    url: jdbc:mysql://148.70.182.192:3306/group_liu?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml